### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by TheDarkCode** [liamca/azure-search-tate-art-gallery#2]
This is what appears when you try to access the [demo link](https://rawgit.com/liamca/azure-search-tate-art-gallery/master/Demo/index.html):

```
500 Internal Server Error

Shit.
```

**Comment by liamca** [comment]
Weird, this is working for me.  Can you try one more time?

**Comment by TheDarkCode** [comment]
Working now. Must have been something with rawgit.com's servers earlier.

http://rawgit.com/faq#no-uptime-guarantee
